### ISSUE TITLE
NullPointerException in set identity, even though I am passing the correct non null identity.

### ISSUE THREAD

**Issue by NaisargiPatel** [NetcoreSolutions/Smartech-Android-FCM-SDK#3]
I have added this crash from the Firebase Crashlytics. More than 130 users are facing this issue. Please resolve asap and revert me back if any changes are required in the code.

Set identity is throwing an error. I have already set a non-null identity then why this internal crash happens?

Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
in.netcore.smartechfcm.NetcoreSDK.setIdentity (SourceFile:329)
-----------------------------------------------------------------------------------------------------------

Fatal Exception: java.lang.RuntimeException: Unable to create application com.kidzapp.MyApplication: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6423)
       at android.app.ActivityThread.access$1300(ActivityThread.java:248)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1830)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7285)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

**Comment by AppCapster** [comment]
This issue solved in the latest release please check.
